/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import ModelDAO.Tables;
import ModelDAO.TablesData;
import Utilities.DBUtility;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static Gui.ThongTinBan.idTable;
import javax.swing.JButton;

/**
 *
 * @author anhquan
 */
public class KhachDatTruoc extends javax.swing.JFrame {

    /**
     * Creates new form KhachDatTruoc
     */
    int id=-1;
    public KhachDatTruoc() {
        initComponents();   
        set();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KhachDat = new javax.swing.JDialog();
        NoteDat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        DatOk = new javax.swing.JButton();
        DatHuy = new javax.swing.JButton();
        Gio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DaDat = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        KhachDen = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        gio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NoteOk = new javax.swing.JTextField();
        Ban5 = new javax.swing.JButton();
        Ban10 = new javax.swing.JButton();
        Ban2 = new javax.swing.JButton();
        Ban9 = new javax.swing.JButton();
        Ban7 = new javax.swing.JButton();
        Ban3 = new javax.swing.JButton();
        Ban6 = new javax.swing.JButton();
        Ban11 = new javax.swing.JButton();
        Ban4 = new javax.swing.JButton();
        Ban8 = new javax.swing.JButton();
        Ban12 = new javax.swing.JButton();
        txtmess = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Ban1 = new javax.swing.JButton();

        KhachDat.setMinimumSize(new java.awt.Dimension(350, 350));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Ghi Chú");

        DatOk.setText("Đồng ý");
        DatOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatOkActionPerformed(evt);
            }
        });

        DatHuy.setText("Quay lại");
        DatHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatHuyActionPerformed(evt);
            }
        });

        jLabel4.setText("Giờ đến:");

        javax.swing.GroupLayout KhachDatLayout = new javax.swing.GroupLayout(KhachDat.getContentPane());
        KhachDat.getContentPane().setLayout(KhachDatLayout);
        KhachDatLayout.setHorizontalGroup(
            KhachDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachDatLayout.createSequentialGroup()
                .addGroup(KhachDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhachDatLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(KhachDatLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(KhachDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KhachDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(KhachDatLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(Gio))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KhachDatLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(DatOk)
                                    .addGap(46, 46, 46)
                                    .addComponent(DatHuy)))
                            .addComponent(NoteDat, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        KhachDatLayout.setVerticalGroup(
            KhachDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachDatLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NoteDat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(KhachDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(KhachDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatOk)
                    .addComponent(DatHuy))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        DaDat.setMinimumSize(new java.awt.Dimension(350, 350));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Ghi Chú");

        KhachDen.setText("Khách đã đến");
        KhachDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachDenActionPerformed(evt);
            }
        });

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Giờ đến");

        javax.swing.GroupLayout DaDatLayout = new javax.swing.GroupLayout(DaDat.getContentPane());
        DaDat.getContentPane().setLayout(DaDatLayout);
        DaDatLayout.setHorizontalGroup(
            DaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaDatLayout.createSequentialGroup()
                .addGroup(DaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DaDatLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2))
                    .addGroup(DaDatLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(KhachDen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DaDatLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(DaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoteOk, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DaDatLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGroup(DaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DaDatLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(DaDatLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        DaDatLayout.setVerticalGroup(
            DaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaDatLayout.createSequentialGroup()
                .addGroup(DaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DaDatLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(DaDatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NoteOk, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DaDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(DaDatLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6))
                    .addGroup(DaDatLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(KhachDen, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ban5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban5.setText(" 5");
        Ban5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban5ActionPerformed(evt);
            }
        });

        Ban10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban10.setText(" 10");
        Ban10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban10ActionPerformed(evt);
            }
        });

        Ban2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban2.setText(" 2");
        Ban2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban2ActionPerformed(evt);
            }
        });

        Ban9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban9.setText(" 9");
        Ban9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban9ActionPerformed(evt);
            }
        });

        Ban7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban7.setText(" 7");
        Ban7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban7ActionPerformed(evt);
            }
        });

        Ban3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban3.setText(" 3");
        Ban3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban3ActionPerformed(evt);
            }
        });

        Ban6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban6.setText(" 6");
        Ban6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban6ActionPerformed(evt);
            }
        });

        Ban11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban11.setText("11");
        Ban11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban11ActionPerformed(evt);
            }
        });

        Ban4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban4.setText(" 4");
        Ban4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban4ActionPerformed(evt);
            }
        });

        Ban8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban8.setText("8");
        Ban8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban8ActionPerformed(evt);
            }
        });

        Ban12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban12.setText("12");
        Ban12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban12ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Bàn Khách Đặt Trước");

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Ban1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table-40.png"))); // NOI18N
        Ban1.setText("1");
        Ban1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ban1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Ban5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ban9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Ban1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ban6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ban2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ban10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Ban3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(Ban4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Ban11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ban12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Ban7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(Ban8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtmess, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(154, 154, 154)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addComponent(txtmess, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ban2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ban3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ban4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ban1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ban8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ban7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ban6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ban5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ban9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ban10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ban11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ban12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatHuyActionPerformed
        // TODO add your handling code here:
        KhachDat.setVisible(false);
        
    }//GEN-LAST:event_DatHuyActionPerformed

    private void Ban2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban2ActionPerformed
        // TODO add your handling code here:
        work("Bàn 2");
    }//GEN-LAST:event_Ban2ActionPerformed

    private void Ban3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban3ActionPerformed
        // TODO add your handling code here:
     work("Bàn 3");
    }//GEN-LAST:event_Ban3ActionPerformed

    private void Ban4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban4ActionPerformed
        // TODO add your handling code here:
        work("Bàn 4");
    }//GEN-LAST:event_Ban4ActionPerformed

    private void Ban5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban5ActionPerformed
        // TODO add your handling code here:
        work("Bàn 5");
    }//GEN-LAST:event_Ban5ActionPerformed

    private void Ban6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban6ActionPerformed
        // TODO add your handling code here:
       work("Bàn 6");
    }//GEN-LAST:event_Ban6ActionPerformed

    private void Ban7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban7ActionPerformed
        // TODO add your handling code here:
        work("Bàn 7");
    }//GEN-LAST:event_Ban7ActionPerformed

    private void Ban8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban8ActionPerformed
        // TODO add your handling code here:
          work("Bàn 8");
    }//GEN-LAST:event_Ban8ActionPerformed

    private void Ban9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban9ActionPerformed
        // TODO add your handling code here:
       work("Bàn 9");
    }//GEN-LAST:event_Ban9ActionPerformed

    private void Ban10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban10ActionPerformed
        // TODO add your handling code here:
       work("Bàn 10");
    }//GEN-LAST:event_Ban10ActionPerformed

    private void Ban11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban11ActionPerformed
        // TODO add your handling code here:
       work("Bàn 11");
    }//GEN-LAST:event_Ban11ActionPerformed

    private void Ban12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban12ActionPerformed
        // TODO add your handling code here:
         work("Bàn 12");
        
    }//GEN-LAST:event_Ban12ActionPerformed

    private void DatOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatOkActionPerformed
          // TODO add your handling code here:
           Connection con = DBUtility.openConnection();
                    PreparedStatement pstmt;
        try {
            pstmt = con.prepareStatement("update tables set status= 3 ,note=?,time=? where ID=?");
             pstmt.setString(1,NoteDat.getText());
             pstmt.setString(2,Gio.getText());
             pstmt.setInt(3, id);      
             pstmt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(KhachDatTruoc.class.getName()).log(Level.SEVERE, null, ex);
        }
               set();
               KhachDat.setVisible(false);
    }//GEN-LAST:event_DatOkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        KhachDat.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void KhachDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhachDenActionPerformed
        // TODO add your handling code here:
               Connection con = DBUtility.openConnection();
                    PreparedStatement pstmt;
        try {
            pstmt = con.prepareStatement("update tables set status= 0 ,note='',time='' where ID=?");
             pstmt.setInt(1, id);
             pstmt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(KhachDatTruoc.class.getName()).log(Level.SEVERE, null, ex);
        }
               idTable=id;
               QuanLyThucDon qlo = new QuanLyThucDon();
                qlo.setVisible(true);
                DaDat.setVisible(false);
                dispose();
    }//GEN-LAST:event_KhachDenActionPerformed

    private void Ban1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ban1ActionPerformed
        // TODO add your handling code here:
           work("Bàn 1");
    }//GEN-LAST:event_Ban1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachDatTruoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachDatTruoc().setVisible(true);
            }
        });
    }
   private int getId(String nameSave) {
        List<Tables> listTable = TablesData.getInstance().LoadListTables();
        for (int i = 0; i < listTable.size(); i++) {
            Tables tables = listTable.get(i);
            if (tables.getTableName().equals(nameSave)) {
                id = tables.getTableId();               
                break;
            }
        }

        return id;
    }
   private int getstatus(int id){
        List<Tables> listTable = TablesData.getInstance().LoadListTables();
        int st=-1;
        for (int i = 0; i < listTable.size(); i++) {
            Tables tables = listTable.get(i);
            if (tables.getTableId()==id) {
                st=tables.getTableStatus();
                break;
            }
        }
        return st;
   }
    private String getnote(int id){
        List<Tables> listTable = TablesData.getInstance().LoadListTables();
        String noteok = null;
        for (int i = 0; i < listTable.size(); i++) {
            Tables tables = listTable.get(i);
            if (tables.getTableId()==id) {
                noteok=tables.getTableNote();
                break;
            }
        }
        return noteok;
   }
    private String gettime(int id){
          List<Tables> listTable = TablesData.getInstance().LoadListTables();
        String time = null;
        for (int i = 0; i < listTable.size(); i++) {
            Tables tables = listTable.get(i);
            if (tables.getTableId()==id) {
                time=tables.getTime();
                break;
            }
        }
        return time;
    }
    private void work(String nameSave){
           id = getId(nameSave);
        if(getstatus(id)==3){
          NoteOk.setText(getnote(id));
          gio.setText(gettime(id));       
          DaDat.setLocationRelativeTo(null);
          DaDat.setVisible(true);
        }
        else if(getstatus(id)==0) {
         KhachDat.setLocationRelativeTo(null);
         KhachDat.setVisible(true);}
        else {
           txtmess.setText("Bàn đã có người sử dụng!");
        }
    }
    private void Setstatus(JButton Ban,String s){
         List<Tables> listTable = TablesData.getInstance().LoadListTables();
           for (int i = 0; i < listTable.size(); i++) {
            Tables tables = listTable.get(i);
                     if (tables.getTableName().equals(s)) {
                if (tables.getTableStatus()==0) {
                    Ban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-tablefree-60.png")));
                } else if(tables.getTableStatus()==3) {
                    Ban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-table1-60.png")));
                }
                else Ban.setEnabled(false);
            }
    }}
    private void set(){
        Setstatus(Ban1,"Bàn 1");
        Setstatus(Ban2,"Bàn 2");
        Setstatus(Ban3,"Bàn 3");
        Setstatus(Ban4,"Bàn 4");
        Setstatus(Ban5,"Bàn 5");
        Setstatus(Ban6,"Bàn 6");
        Setstatus(Ban7,"Bàn 7");
        Setstatus(Ban8,"Bàn 8");
        Setstatus(Ban9,"Bàn 9");
        Setstatus(Ban10,"Bàn 10");
        Setstatus(Ban11,"Bàn 11");
        Setstatus(Ban12,"Bàn 12");      
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ban1;
    private javax.swing.JButton Ban10;
    private javax.swing.JButton Ban11;
    private javax.swing.JButton Ban12;
    private javax.swing.JButton Ban2;
    private javax.swing.JButton Ban3;
    private javax.swing.JButton Ban4;
    private javax.swing.JButton Ban5;
    private javax.swing.JButton Ban6;
    private javax.swing.JButton Ban7;
    private javax.swing.JButton Ban8;
    private javax.swing.JButton Ban9;
    private javax.swing.JDialog DaDat;
    private javax.swing.JButton DatHuy;
    private javax.swing.JButton DatOk;
    private javax.swing.JTextField Gio;
    private javax.swing.JDialog KhachDat;
    private javax.swing.JButton KhachDen;
    private javax.swing.JTextField NoteDat;
    private javax.swing.JTextField NoteOk;
    private javax.swing.JLabel gio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel txtmess;
    // End of variables declaration//GEN-END:variables
}
