/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import ModelDAO.AccountData;
import ModelDAO.DrinksData;
import ModelDAO.InvoicesDAO;
import ModelDAO.MenuData;
import ModelDAO.OrderData;
import ModelDAO.Drinks;
import ModelDAO.Menu;
import static Gui.ThongTinBan.idTable;
import Utilities.DBUtility;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author huyparody
 */
public class QuanLyThucDon extends javax.swing.JFrame {

        /**
         * Creates new form QuanLyThucDon
         */
        
        DefaultComboBoxModel<Drinks> comboBoxModel;
        DefaultTableModel tableModel;
        DefaultTableModel drinksModel;
        int totalPrice = 0;
        int index=0;
        int check=0;//check pay
        public QuanLyThucDon() {
            
                initComponents();
             
                txtDisplay.setText("Xin chao: " + AccountData.getInstance().GetAccount().getName());
                tableModel = new DefaultTableModel();
                tableModel.addColumn("STT");
                tableModel.addColumn("Tên đồ uống");
                tableModel.addColumn("Giá"); 
                tableModel.addColumn("Số lượng trong kho");  
                tblTables.setModel(tableModel);
                displayMenuDrinks();

                drinksModel = new DefaultTableModel();
                drinksModel.addColumn("STT");
                drinksModel.addColumn("Tên đồ uống");
                drinksModel.addColumn("Giá");
                drinksModel.addColumn("Số lượng");
                drinksModel.addColumn("Thành tiền");
                drinksModel.addColumn("Ghi chú");
                tblOrder.setModel(drinksModel);

                comboBoxModel = new DefaultComboBoxModel<>();
             
                loadDrinks();
                displayTableDrinks();
                if(check==1){
                    btnPay.setEnabled(true);
                    check=1;
                }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Oder = new javax.swing.JDialog();
        GhiChu = new javax.swing.JTextField();
        SoLuong = new javax.swing.JSpinner();
        OK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Huy = new javax.swing.JButton();
        hetsanpham = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        Khongdusanpham = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTables = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnPay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        txtDisplay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nhantukhach = new javax.swing.JTextField();
        jlbcomeback = new javax.swing.JLabel();
        Tralaikhach = new javax.swing.JTextField();
        btprint = new javax.swing.JButton();

        Oder.setMinimumSize(new java.awt.Dimension(400, 400));

        GhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GhiChuActionPerformed(evt);
            }
        });

        OK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OK.setText("Chọn ");
        OK.setActionCommand("");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ghi chú :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-order-50.png"))); // NOI18N
        jLabel6.setText("    Oder");

        Huy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Huy.setText("Hủy");
        Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OderLayout = new javax.swing.GroupLayout(Oder.getContentPane());
        Oder.getContentPane().setLayout(OderLayout);
        OderLayout.setHorizontalGroup(
            OderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OderLayout.createSequentialGroup()
                .addGroup(OderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OderLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OderLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OderLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        OderLayout.setVerticalGroup(
            OderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addGroup(OderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(OderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(OderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        hetsanpham.setMinimumSize(new java.awt.Dimension(450, 90));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("Sản phẩm trong kho đã hết");

        javax.swing.GroupLayout hetsanphamLayout = new javax.swing.GroupLayout(hetsanpham.getContentPane());
        hetsanpham.getContentPane().setLayout(hetsanphamLayout);
        hetsanphamLayout.setHorizontalGroup(
            hetsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hetsanphamLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        hetsanphamLayout.setVerticalGroup(
            hetsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hetsanphamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Khongdusanpham.setMinimumSize(new java.awt.Dimension(500, 100));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Sản phẩm trong kho không đủ");

        javax.swing.GroupLayout KhongdusanphamLayout = new javax.swing.GroupLayout(Khongdusanpham.getContentPane());
        Khongdusanpham.getContentPane().setLayout(KhongdusanphamLayout);
        KhongdusanphamLayout.setHorizontalGroup(
            KhongdusanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhongdusanphamLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        KhongdusanphamLayout.setVerticalGroup(
            KhongdusanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhongdusanphamLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý bán hàng");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-restaurant-menu-50.png"))); // NOI18N
        jLabel1.setText("Quản lý bán hàng");

        tblTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTables.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblTablesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblTables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTables);

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblOrder);

        btnPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/Cash in Hand_50px.png"))); // NOI18N
        btnPay.setText("Thanh toán");
        btnPay.setEnabled(false);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tổng tiền :");

        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalPrice.setText("0");
        txtTotalPrice.setEnabled(false);
        txtTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPriceActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/Go Back_50px.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        txtDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDisplay.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nhận từ khách :");

        Nhantukhach.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nhantukhach.setText("0");
        Nhantukhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhantukhachActionPerformed(evt);
            }
        });

        jlbcomeback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbcomeback.setText("Trả lại khách :");

        Tralaikhach.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Tralaikhach.setText("0");
        Tralaikhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TralaikhachActionPerformed(evt);
            }
        });

        btprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/icons8-print-50.png"))); // NOI18N
        btprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbcomeback, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tralaikhach, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(Nhantukhach, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtTotalPrice))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnPay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btprint, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nhantukhach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbcomeback, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tralaikhach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btprint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
          try {
                    // TODO add your handling code here:
                    int invoiceId = InvoicesDAO.getInstance().GetUncheckInvoiceByTableId(idTable);
                    InvoicesDAO.getInstance().Update(invoiceId, totalPrice);
                    Connection con = DBUtility.openConnection();
                    PreparedStatement pstmt = con.prepareStatement("update tables set status=0 where ID=?");
                    pstmt.setInt(1, idTable);
                    pstmt.executeUpdate();
                    Nhantukhach.setText("0");
                    Tralaikhach.setText("0");
                    displayMenuDrinks();
                    displayTableDrinks();
                    btnPay.setEnabled(false);
            } catch (SQLException ex) {
                    Logger.getLogger(QuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
            ThongTinBan tt = new ThongTinBan();
            tt.setVisible(true);
            dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPriceActionPerformed

    private void NhantukhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhantukhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhantukhachActionPerformed

    private void TralaikhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TralaikhachActionPerformed
        // TODO add your handling code here:
        Tinhtien();
    }//GEN-LAST:event_TralaikhachActionPerformed

    private void btprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprintActionPerformed
        // TODO add your handling code here:
     dispose(); 
    }//GEN-LAST:event_btprintActionPerformed

    private void tblTablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablesMouseClicked
        if(evt.getClickCount()>=1){
           index=tblTables.getSelectedRow();
          int a=(int) tblTables.getValueAt(index,3);
          if(a==0){
              hetsanpham.setLocationRelativeTo(null);
              hetsanpham.setVisible(true);
          }
          else{
           Oder.setLocationRelativeTo(null);
           Oder.setVisible(true);
       }}
    }//GEN-LAST:event_tblTablesMouseClicked

    private void tblTablesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblTablesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTablesAncestorAdded

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
         int invoiceId = InvoicesDAO.getInstance().GetUncheckInvoiceByTableId(idTable);//check xem trang thai cua ban,dua ra invoiceid=-1 neu ban dang dung
            List<Drinks> listDrinks=DrinksData.getInstance().GetListDrink();
            Drinks drinks=listDrinks.get(index);
            int giam=Integer.parseInt(SoLuong.getValue().toString());
            int slcl=drinks.getSoluong();//so luong trong kho
            if(slcl<giam){
                Khongdusanpham.setLocationRelativeTo(null);
                Khongdusanpham.setVisible(true);
            }
            else{
            if (invoiceId == -1) {
                    InvoicesDAO.getInstance().Insert(idTable, AccountData.getInstance().GetAccount().getId());
                    OrderData.getInstance().Insert(drinks.getId(), InvoicesDAO.getInstance().GetMaxIdInvoice(), Integer.parseInt(SoLuong.getValue().toString()),GhiChu.getText());
                     //update so luong con l
                    Connection con = DBUtility.openConnection();                 
            try {
                PreparedStatement pstmt = con.prepareStatement("update drinks set soluong=? where ID=?");
               
                int conl=slcl-giam; //so luong ocn lai sau khi ban
                pstmt.setInt(1,conl);
                pstmt.setInt(2,drinks.getId());
                int i = pstmt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyDoUong.class.getName()).log(Level.SEVERE, null, ex);
            }
      
        
                     
            } else {
                    OrderData.getInstance().Insert(drinks.getId(), invoiceId, Integer.parseInt(SoLuong.getValue().toString()),GhiChu.getText());
                    Connection con = DBUtility.openConnection();
            try {
                PreparedStatement pstmt = con.prepareStatement("update drinks set soluong=? where ID=?");
                int conl=slcl-giam;
                pstmt.setInt(1,conl);
                pstmt.setInt(2,drinks.getId());
                int i = pstmt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyDoUong.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            Connection con = DBUtility.openConnection();
            PreparedStatement pstmt;
            try {
                    pstmt = con.prepareStatement("update tables set status=1 where ID=?");
                    pstmt.setInt(1, idTable);
                    pstmt.executeUpdate();
                    displayMenuDrinks();
                    displayTableDrinks();
                    btnPay.setEnabled(true);               
                    Oder.setVisible(false);
                    
            } catch (SQLException ex) {
                    Logger.getLogger(QuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_OKActionPerformed

    private void GhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GhiChuActionPerformed

    private void HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyActionPerformed
        // TODO add your handling code here:
       Oder.setVisible(false);
                    
    }//GEN-LAST:event_HuyActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Windows".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(QuanLyThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(QuanLyThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(QuanLyThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(QuanLyThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new QuanLyThucDon().setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GhiChu;
    private javax.swing.JButton Huy;
    private javax.swing.JDialog Khongdusanpham;
    private javax.swing.JTextField Nhantukhach;
    private javax.swing.JButton OK;
    private javax.swing.JDialog Oder;
    private javax.swing.JSpinner SoLuong;
    private javax.swing.JTextField Tralaikhach;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btprint;
    private javax.swing.JDialog hetsanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbcomeback;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblTables;
    private javax.swing.JLabel txtDisplay;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables

        private void displayMenuDrinks() {
    
             tableModel.setRowCount(0);
            List<Drinks> listDrinks = DrinksData.getInstance().GetListDrink();
            for (int i = 0; i < listDrinks.size(); i++) {
            Drinks drinks = listDrinks.get(i);
            Object[] dt = {i + 1,drinks.getName(),drinks.getPrice(),drinks.getSoluong()};
            tableModel.addRow(dt);
            }
        }

        private void displayTableDrinks() {
                drinksModel.setRowCount(0);
                totalPrice=0;
                List<Menu> listMenu = MenuData.getInstance().GetListMenuByTableId(idTable);
                for (int i = 0; i < listMenu.size(); i++) {
                        Menu menu = listMenu.get(i);
                        Object[] dt = {i + 1, menu.getDrinkName(), menu.getPrice(), menu.getCount(), menu.getTotalPrice(),menu.getNote()};
                        totalPrice += menu.getTotalPrice();
                        drinksModel.addRow(dt);
                        check=1;
                }
                txtTotalPrice.setText(totalPrice + "");
        }

        private void loadDrinks() {
                List<Drinks> listDrink = DrinksData.getInstance().GetListDrink();
                for (Drinks drinks : listDrink) {
                        comboBoxModel.addElement(drinks);
                }
        }
        
        private void Tinhtien(){
               int tongtien, nhantien, tratien;
        tongtien= totalPrice;
        nhantien= Integer.parseInt(Nhantukhach.getText());
        tratien=  nhantien - totalPrice ;
        Tralaikhach.setText(String.valueOf(tratien));
        }
}
